calibrated: 1
equilibrium:
    sign: -1
    signFlexor: -1
    signExtensor: -1
    nameFlexor: "left_wrist_flexor"
    nameExtensor: "left_wrist_extensor"
    servoRange: 5.4978
    servoOffset: 0
signEncoder: -1
signJoint: 1
name: "left_wrist_pitch"
nameEncoder: "left_wrist_encoder"
minAngle: -0.7
maxAngle: 0.7
maxAbsForwardError: 5.0
gains:
    P: 0.055
    I: 0.0005
    D: 0.2
